version: '3.7'

services:
    golang:
        build:
            context: .
        volumes:
            - ./:/var/www/html
        ports:
            - 8080:80
        restart: unless-stopped
        command: bash -c "go mod download && make serve"

    db:
        image: mariadb:10.4
        volumes:
            - db:/var/lib/mysql:rw
        ports:
            - 3306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_DATABASE: welsh
        restart: on-failure

volumes:
    db: {}