// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package welshacademy

import (
	"database/sql"
	"github.com/joho/godotenv"
	"os"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from container.go:

func InitApp() (*App, error) {
	db := getDBMysql()
	app := &App{
		DBMysql: db,
	}
	return app, nil
}

// container.go:

type App struct {
	DBMysql *sql.DB
}

func Boot() (*App, error) {
	godotenv.Load()

	return InitApp()
}

func getDBMysql() *sql.DB {
	db, err := sql.Open("mysql", os.Getenv("DATABASE_URL")+"?multiStatements=true")

	if err != nil {
		panic(err)
	}

	return db
}
